### ISSUE TITLE
Phase 3: Implement beginner-friendly error messages

### ISSUE THREAD

**Issue by norrisaftcc** [norrisaftcc/tool-algoflow-hs#35]
## Overview

Replace cryptic type errors with actionable, beginner-friendly error messages that guide users to solutions.

## Problem

Current error messages are intimidating:
```
Couldn't match type 'Workflow m0 Int Int' with 'Int -> m Int'
Expected type: Flow (Int -> m Int) (Int -> m String)  
Actual type: Flow (Workflow m0 Int Int) (Workflow m0 Int String)
```

## Solution

Implement custom error handling that provides:
1. **What went wrong** in plain English
2. **Why it went wrong** with context
3. **How to fix it** with examples

### Option 1: Custom Type Errors (GHC 8.0+)
```haskell
type family WorkflowError (msg :: Symbol) :: Constraint where
  WorkflowError msg = TypeError ('Text "Workflow Error: " ':<>: 'Text msg)

-- Usage
instance (WorkflowError "Cannot compose workflows of incompatible types. Did you forget 'runWorkflow'?") 
  => Category (BadWorkflow a)
```

### Option 2: Smart Constructors with Either
```haskell
stepSafe :: String -> (a -> IO b) -> Either WorkflowError (Flow a b)
stepSafe name f 
  | null name = Left (EmptyStepName "Steps must have non-empty names")
  | otherwise = Right (Step name f)
```

### Option 3: Template Haskell for Better Errors
```haskell
-- Compile-time validation with helpful errors
$(makeWorkflow 
  [ step "fetch" fetchData
  , step "process" processData  -- TH checks type compatibility
  ])
```

## Common Errors to Address

- [ ] Type mismatch in workflow composition
- [ ] Missing runWorkflow call
- [ ] Incorrect operator usage (>>> vs >>=)
- [ ] Cache key type mismatches
- [ ] Parallel composition type errors
- [ ] Monad constraint issues

### Before:
```
No instance for (Arrow ((->) Int))
```

### After:
```
Workflow Error: Cannot use regular functions with workflow operators.
  
  You wrote:  processData >>> saveData
  But 'processData' is a regular function, not a workflow step.
  
  Fix: Wrap it in a step:
    step "process" processData >>> step "save" saveData
```

## Success Criteria

- [ ] Common beginner mistakes produce helpful errors
- [ ] Error messages include examples of correct usage
- [ ] No regression in type safety
- [ ] Errors point to likely solutions
- [ ] Can be toggled off for advanced users

## Technical Considerations

- Must work with GHC 9.4+
- Should not impact runtime performance
- Consider IDE integration (HLS)
- Balance between helpful and overwhelming
